In [9]:
import numpy as np

In [127]:
arr = np.random.randint(101, size = (10, 10)) 
print(arr)

[[ 34  15  94  44  99  64  47  30  87  96]
 [ 66   9  47  83  29  55  21  63  63  18]
 [ 13  31  27  30  36  32  30  75  30  99]
 [ 79  13   9  59  99  39  10 100  54  87]
 [ 51  80  54  89  66  20   5  28  88  74]
 [  5  30  76  40  45  82  93  22  79  67]
 [ 35   5   9  16  23  69  87  79  80  81]
 [ 17  60  85  22  11  80  33  20  89  92]
 [ 26  65  54  82  26  14   1  95  55  18]
 [ 23  20  65  69  58  96  30  59  93  29]]


In [128]:
mediana = np.median(arr)
print(mediana)


52.5


In [13]:
def soma(x,y):
    if y > x:
        s = 0
        for i in range(x,y+1):
            s+=i
        print(s)
    else:
        print('O segundo número não é maior que o primeiro, digite outros valores!') 

In [189]:
import random   
n = random.choice(arr)
num1 = random.choice(n)
num2 = random.choice(n)
print(f'{num1},{num2}')
soma(num1,num2)


35,9
O segundo número é menor que o primeiro, digite outros valores!


In [72]:
def fat(num_fatorial):
    s=0
    if num_fatorial > 0:
        s = 1
        for n in range(1,num_fatorial+1):
            s *= n
    print(s)

In [182]:
num = random.choice(arr)
num3 = random.choice(num)
print(num)
print(num3)
fat(num3)

[26 65 54 82 26 14  1 95 55 18]
1
1
