In [1]:
import numpy as np

In [18]:
np.random.seed(10)

In [19]:
arr = np.random.randint(101, size = (10, 10)) 
print(arr)

[[  9 100  15  64  28  89  93  29   8  73]
 [  0  40  36  16 100  11  54  88  62  33]
 [ 72 100  78  49  51  54  77  69  13  25]
 [ 13  92  86  30  30  89  12  65  31  57]
 [ 36  27  18  93  77  22  23  94  11  28]
 [ 74  88   9  15  18  80  71  88  11  17]
 [ 46   7  75  28  33  84  96  88  44   5]
 [  4  71  88  88  50  54  34  15  77  88]
 [ 15   6  85  22  11  12  92  96  62  57]
 [ 79  42  57  97  50  45  40  89  73  37]]


In [20]:
mediana = np.median(arr)
media = np.mean(arr)
variancia = np.var(arr)
dp = np.std(arr)
print(f"Mediana: {mediana}\nMédia: {media}\nVariância: {variancia}\nDesvio Padrão: {dp}")


Mediana: 50.0
Média: 50.83
Variância: 956.8211
Desvio Padrão: 30.932524953517778


In [12]:
def soma(x,y):
    if y > x:
        s = np.arange(x,y+1).sum()
        print(s)
    else:
        print('O segundo número não é maior que o primeiro, digite outros valores!') 

In [16]:
soma(5,4)

O segundo número não é maior que o primeiro, digite outros valores!


In [22]:
import random   
n = random.choice(arr)
num1 = random.choice(n)
num2 = random.choice(n)
print(f'{num1},{num2}')
soma(num1,num2)


36,40
190


In [2]:
def fat(num_fatorial):
    if num_fatorial > 0:
        s = np.arange(1,num_fatorial+1).prod()
        print(s)

In [3]:
fat(5)

120


In [27]:
num = random.choice(arr)
num3 = random.choice(num)
print(num)
print(num3)
fat(num3)

[36 27 18 93 77 22 23 94 11 28]
27
10888869450418352160768000000
